import { config as dotenvConfig } from "dotenv";
dotenvConfig();
const {
	PORT,
	DB_NAME,
	DB_USERNAME,
	DB_PASSWORD,
	DB_HOST,
	DB_PORT,
	DB_CLIENT,
	JWT_ALGORITHM,
	JWT_EXPIRATION_TIME,
	JWT_SECRET,
	ENCRYPTION_ALGORITHM,
	ENCRYPTION_SALT_ROUNDS,
	ENCRYPTION_SECRET,
} = process.env;
const config = {
	APP: {
		API_PATH: "/api",
		PORT: PORT,
	},
	DB: {
		DATABASE: DB_NAME,
		USERNAME: DB_USERNAME,
		PASSWORD: DB_PASSWORD,
		HOST: DB_HOST,
		PORT: DB_PORT,
		CLIENT: DB_CLIENT,
		DEBUG: false,
	},
	JWT: {
		ALGORITHM: JWT_ALGORITHM,
		EXPIRATION_TIME: JWT_EXPIRATION_TIME,
		SECRET: JWT_SECRET,
	},
	ENCRYPTION: {
		ALGORITHM: ENCRYPTION_ALGORITHM,
		SALT_ROUNDS: ENCRYPTION_SALT_ROUNDS,
		SECRET: ENCRYPTION_SECRET,
	},
};
export { config };
